version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: PhysioDB
      POSTGRES_USER: adminJD
      POSTGRES_PASSWORD: qwerty1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://:qwerty1234@db:5432/PhysioDB

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000

volumes:
  postgres_data:
